// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "PointCloudGenerator.h"
#include "GalaxyDataGenerator.generated.h"
/// <summary>
///	GALAXY GENERATION PARAM STRUCT
/// </summary>
USTRUCT(BlueprintType)
struct SVO_API FGalaxyParams {
	GENERATED_BODY()
	// Generation parameters (affect WHAT is generated)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	int Seed = 69;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	double Extent = 2147483648;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Generation")
	double UnitScale = 1e11; //Dervied value, this should always be generated by the spawning actor

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	double MinStarSystemScale = 1.496e12;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	double MaxStarSystemScale = 1.496e16;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	FRotator Rotation = FRotator::ZeroRotator;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	FRuntimeFloatCurve ScaleDistributionCurve;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Generation")
	FLinearColor ParentColor = FLinearColor(1, 1, 1, 0);

	//Base Params - control overall sizes
	double GalaxyRatio = .30;
	double BulgeRatio = .75;
	double VoidRatio = .033;

	//Twist Params - Alters the behavior of the twist pass
	double TwistStrength = 4;
	double TwistCoreRadius = .01;
	double TwistCoreTwistExponent = 1;
	double TwistCoreStrength = 4;

	//Arm Params - changes arm appearance
	int ArmNumPoints = 75000; //Total arm points to generate
	int ArmNumArms = 4; //Number of arms
	int ArmClusters = 124; //Number of clusters per arm
	double ArmDepthBias = .5; //Smaller number = more large stars, larger number = more small stars, at 1 it will use a basic stellar size distribution table
	double ArmBaseDensity = 3; //Base density factor
	double ArmClusterRadiusMin = .05; //Cluster scale ramp start  
	double ArmClusterRadiusMax = .3; //Cluster scale ramp end
	double ArmSpreadMin = .05; //Base cluster scale
	double ArmSpreadMax = .3; //Height value = more scattered arms
	double ArmStartRatio = .5; //Where will the arm start relative to the bulge
	double ArmHeightRatio = .5; //Height squish
	double ArmProgressExponent = 1;
	double ArmRadialDensityExponent = 2; //ScaleFactor falloff towards center
	double ArmRadialDensityMax = 8; //ScaleFactor multiplier as points are further from center
	double ArmRadialDensityMin = .5; //Min radial density multiplier

	//Bulge Params - Controls the galactic bulge
	int BulgeNumPoints = 75000;
	double BulgeBaseDensity = 2;
	double BulgeDepthBias = .75;
	double BulgeRadiusScale = .33;
	double BulgeTruncationScale = 1;
	double BulgeAcceptanceExponent = 2;
	double BulgeJitter = .2;
	FVector BulgeAxisScale = FVector(1, 1, .6);

	//Cluster Params
	int ClusterNumPoints = 50000;
	int ClusterNumClusters = 128;
	FVector ClusterAxisScale = FVector(1, 1, 1);
	double ClusterSpreadFactor = .35;
	double ClusterMinScale = .3;
	double ClusterMaxScale = .7;
	double ClusterIncoherence = 3;
	double ClusterBaseDensity = 1;
	double ClusterDepthBias = 1;

	//Disc Params - Controls the non spiral disc
	int DiscNumPoints = 50000;
	double DiscBaseDensity = 1;
	double DiscDepthBias = 1;
	double DiscHeightRatio = .1;

	//Background Params - Controls the background halo 
	int BackgroundNumPoints = 50000;
	double BackgroundBaseDensity = 10;
	double BackgroundDepthBias = 1;
	double BackgroundHeightRatio = .8;

	//Volume Material Params
	FLinearColor VolumeAmbientColor = FLinearColor(1, 1, 1, 1);
	FLinearColor VolumeCoolShift = FLinearColor(.2, .5, .8);
	FLinearColor VolumeHotShift = FLinearColor(.5, 1.5, 3);
	double VolumeHueVariance = .1;
	double VolumeHueVarianceScale = .5;
	double VolumeSaturationVariance = .1;
	double VolumeTemperatureInfluence = 32;
	double VolumeTemperatureScale = 1;
	double VolumeDensity = .5;
	double VolumeWarpAmount = .05;
	double VolumeWarpScale = .33;
	FString VolumeNoise = "/svo/VolumeTextures/VT_PerlinWorley_Balanced";

	double GalaxyRadius;
	double BulgeRadius;
	double VoidRadius;

	FGalaxyParams() {
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.0f, 0.0f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.25f, 0.001f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.75f, 0.005f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.9375f, 0.01f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.984375f, 0.05f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.996f, 0.1f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(0.999f, 0.4f);
		ScaleDistributionCurve.GetRichCurve()->AddKey(1.0f, 1.0f);
	}
};

/// <summary>
/// GALAXY PARAM FACTORY CONSTRUCTOR - DEFINES RANDOMIZATION RANGES AND ARCHTYPES
/// </summary>
class SVO_API GalaxyParamFactory {
public:

	int Seed = 666;
	//Galaxy archtypes
	FGalaxyParams E0;
	FGalaxyParams E3;
	FGalaxyParams E5;
	FGalaxyParams E7;
	FGalaxyParams S0;
	FGalaxyParams Sa;
	FGalaxyParams Sb;
	FGalaxyParams Sc;
	FGalaxyParams SBa;
	FGalaxyParams SBb;
	FGalaxyParams SBc;
	FGalaxyParams Irr;

	//Bounds
	FGalaxyParams E0_Min;  FGalaxyParams E0_Max;
	FGalaxyParams E3_Min;  FGalaxyParams E3_Max;
	FGalaxyParams E5_Min;  FGalaxyParams E5_Max;
	FGalaxyParams E7_Min;  FGalaxyParams E7_Max;
	FGalaxyParams S0_Min;  FGalaxyParams S0_Max;
	FGalaxyParams Sa_Min;  FGalaxyParams Sa_Max;
	FGalaxyParams Sb_Min;  FGalaxyParams Sb_Max;
	FGalaxyParams Sc_Min;  FGalaxyParams Sc_Max;
	FGalaxyParams SBa_Min; FGalaxyParams SBa_Max;
	FGalaxyParams SBb_Min; FGalaxyParams SBb_Max;
	FGalaxyParams SBc_Min; FGalaxyParams SBc_Max;
	FGalaxyParams Irr_Min; FGalaxyParams Irr_Max;

	//Stand alone volume material bounds
	FGalaxyParams Volume_Min; FGalaxyParams Volume_Max;

	TArray<TPair<float, FGalaxyParams*>> GalaxyWeights = { {0.02f, &E0}, {0.04f, &E3}, {0.04f, &E5}, {0.03f, &E7}, {0.1f, &S0}, {0.2f, &Sa}, {0.2f, &Sb}, {0.22f, &Sc}, {0.04f, &SBa}, {0.04f, &SBb}, {0.03f, &SBc}, {0.04f, &Irr} };
	TArray<const char*> NoisePaths = {
		"/svo/VolumeTextures/VT_PerlinWorley_Balanced",
		"/svo/VolumeTextures/VT_PerlinWorley_Balanced",
		"/svo/VolumeTextures/VT_PerlinWorley_Balanced",
		"/svo/VolumeTextures/VT_Gradient_l5_256",
		"/svo/VolumeTextures/VT_Gradient_Turbulence_l5_256",
		"/svo/VolumeTextures/VT_Voronoi_l5_256",
		"/svo/VolumeTextures/VT_Gradient_l3_256",
		"/svo/VolumeTextures/VT_Gradient_Turbulence_l3_256",
		"/svo/VolumeTextures/VT_Voronoi_l3_256",
		"/svo/VolumeTextures/VT_Gradient_l1_256",
		"/svo/VolumeTextures/VT_Gradient_Turbulence_l1_256",
		"/svo/VolumeTextures/VT_Voronoi_l1_256"
	};

	GalaxyParamFactory();

	FGalaxyParams GenerateParams();
	FGalaxyParams BoundedRandomizeParams(FGalaxyParams MinParams, FGalaxyParams MaxParams);
	int SelectGalaxyTypeIndex();
};

/// <summary>
///GALAXY GENERATOR - GENERATES DATA FOR POPULATING A GALAXY
/// </summary>
class SVO_API GalaxyDataGenerator : public PointCloudGenerator {
public:
	GalaxyDataGenerator() : PointCloudGenerator(69) {};
	GalaxyDataGenerator(int InSeed) : PointCloudGenerator(InSeed) {};

	FGalaxyParams Params;

	TArray<FPointData> GeneratedData;

	virtual void GenerateData(TSharedPtr<FOctree> InOctree) override;

	void GenerateArms();
	void ApplyTwist();
	void GenerateBulge();
	void GenerateClusters();
	void GenerateDisc();
	void GenerateBackground();
	void ApplyRotation();
	void GenerateCluster(int InSeed, FVector InClusterCenter, FVector InClusterRadius, int InCount, double InBaseDensity = 1, double InDepthBias = 1);
};
