// GalaxyArchetype.h
// One galaxy morphology, as an asset.
//
// SPLIT OF OWNERSHIP: this asset says what a spiral IS. FGalaxyArchetypeEntry, on the
// universe actor, says how common spirals are HERE. The same asset can be referenced by
// several universes at different weights, and duplicating it is how "Barred" gets made
// from "Spiral" without touching code.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "Engine/VolumeTexture.h"
#include "GalaxyParams.h"
#include "GalaxyArchetype.generated.h"

/** One rolled parameter: which one, and the closed interval it rolls over.
 *
 *  SPARSE ON PURPOSE. FGalaxyProceduralParams has 61 members and a given morphology
 *  varies maybe twenty of them. A Min/Max pair of whole structs would force all 61 to
 *  be authored twice with nothing distinguishing "rolls between 2 and 6" from "is 4 in
 *  both copies because it does not roll". Here the list IS the answer to what rolls,
 *  and Min sits next to Max on one row instead of in two separately collapsed trees. */
USTRUCT(BlueprintType)
struct ULTRALARGESCALE_API FGalaxyParamRange
{
	GENERATED_BODY()

	/** Property name on FGalaxyProceduralParams. Vector and colour members take a
	 *  COMPONENT SUFFIX -- "NoiseOffset.X", "NoiseChannelWeights.R" -- which keeps one
	 *  flat namespace and one dropdown rather than a conditional component field.
	 *
	 *  The dropdown is generated by reflection over the struct itself
	 *  (GetRollableParameterNames), so renaming a member removes the stale entry from
	 *  the list rather than leaving a name that silently resolves to nothing. Validate
	 *  still catches an already-authored stale name. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Range",
		meta = (GetOptions = "/Script/UltraLargeScale.GalaxyArchetype.GetRollableParameterNames"))
	FName Parameter;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Range")
	float Min = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Range")
	float Max = 0.0f;

	/** Distribution shape: the roll is Lerp(Min, Max, pow(FRand(), Bias)).
	 *
	 *    1     uniform
	 *    > 1   clusters toward MIN  -- most galaxies ordinary, a few extreme
	 *    < 1   clusters toward MAX
	 *
	 *  One float instead of a distribution enum because the thing actually wanted is
	 *  almost always "mostly modest, occasionally dramatic", and an enum would need a
	 *  parameter block per entry to say how much. Anything this cannot express belongs
	 *  in ApplyGenerationLogic, where it can be written directly. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Range", meta = (ClampMin = "0.01"))
	float Bias = 1.0f;

	/** Snap the result to a multiple of this. 0 leaves it continuous.
	 *
	 *  REQUIRED FOR COUNTS. ArmCount is a float like everything else, so a uniform roll
	 *  over 2..6 yields 3.7 arms -- the derivation takes it seriously and the result is
	 *  neither three arms nor four. Quantize 1 is the fix, and there is no way to
	 *  express it with bounds alone. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Range", meta = (ClampMin = "0.0"))
	float Quantize = 0.0f;
};

/** A galaxy morphology: one hand-authored exemplar plus what varies around it.
 *
 *  The field supports every morphology by ZEROING LAYERS, and that is free rather than
 *  merely cheap: SampleLayersWarped early-outs on ArmDensityOverPath > 0, and the disc
 *  and spheroid layers do the same, so a globular with ArmDensity = 0 skips the entire
 *  arm merge loop including the sixteen arm hashes -- most of the field's cost. DO NOT
 *  replace those guards with a lerp or a max when tidying.
 *
 *    Globular   bulge only, high BulgeConcentration, BulgeVerticalRatio ~ 1,
 *               ArmDensity = 0, DiscDensity = 0
 *    Disc       disc + bulge, ArmDensity = 0
 *    Spiral     all four layers
 *
 *  SUBCLASS WHEN THE ROLLS NEED LOGIC. Ranges cover independent parameters drawn
 *  over an interval, which is most of them. Anything else -- a parameter DERIVED from
 *  another, a group that must move together, a rule like "if there is no disc the arms
 *  cannot host" -- goes in an ApplyGenerationLogic override on a subclass of this
 *  asset. That override IS the kickoff's MakeSpiralParams; the router is gone because
 *  virtual dispatch replaced it, and the exemplar sits in the same class as the logic
 *  that rolls around it.
 *
 *  A morphology that is only DIFFERENT NUMBERS needs no subclass -- duplicate the asset
 *  and retune. "Barred" is a duplicate until the bar length has to track arm pitch.
 *
 *      UCLASS()
 *      class UGalaxySpiralArchetype : public UGalaxyArchetype
 *      {
 *          GENERATED_BODY()
 *      protected:
 *          virtual void ApplyGenerationLogic(FGalaxyProceduralParams& InOut,
 *                                            int32 InSeed) const override
 *          {
 *              // Runs AFTER Ranges, so rolled values are readable and correctable.
 *              FRandomStream S = ParameterStream(TEXT("Spiral.ArmHosting"), InSeed);
 *              InOut.Arms.ArmHostFalloff = InOut.Disc.DiscDensity > 0.0f
 *                  ? S.FRandRange(0.5f, 2.0f)
 *                  : 0.0f;
 *          }
 *      };
 */
UCLASS(BlueprintType, Blueprintable)
class ULTRALARGESCALE_API UGalaxyArchetype : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	/** The hand-authored exemplar. Used verbatim in default mode, and it is the base
	 *  every roll is applied on top of -- a parameter absent from Ranges keeps this
	 *  value. Authored in full because a globular genuinely differs from a spiral
	 *  across most of the struct; this is not redundancy. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Exemplar")
	FGalaxyProceduralParams Default;

	/** What varies, and by how much. Everything not listed here is fixed at its
	 *  exemplar value. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rolls")
	TArray<FGalaxyParamRange> Ranges;

	/** Candidate field textures, one drawn per galaxy from each bag.
	 *
	 *  BAGS, NOT RANGES. A texture is categorical: it is chosen from a set, and a Min/Max
	 *  pair for it means nothing. EMPTY is the normal state for all four -- the exemplar's
	 *  own choice is kept, and AGalaxyActor::InitializeData substitutes its default asset
	 *  if that is unset too.
	 *
	 *  FOUR BAGS, ROLLED INDEPENDENTLY, replacing the single NoiseTextures bag. The field
	 *  now reads four textures rather than one -- see FGalaxyProceduralParams -- and each
	 *  wants its own candidates, because the four are not interchangeable: the warp pair
	 *  must be SIGNED vector volumes and the modulation pair UNORM multinoise. Putting a
	 *  multinoise volume in a warp bag translates the family instead of displacing it.
	 *
	 *  INDEPENDENT ROLLS ARE THE POINT, not an implementation detail. A single shared index
	 *  would lock the four choices together, so the bags would produce only as many
	 *  distinct galaxies as the SHORTEST bag has entries; separate streams give the full
	 *  product. Three ridged disc volumes and two halo volumes is six combinations, not two.
	 *
	 *  THIS IS WHERE RIDGING LIVES. A uniform folding every channel at sample time would be
	 *  one value shared by gas and halo, and no setting suits both families. Fill
	 *  NoiseDiscTextures with ridged bakes and NoiseHaloTextures with smooth ones and each
	 *  family gets what it wants for free.
	 *
	 *  WIRED BUT UNCURATED. All four default empty, in which case no roll happens and every
	 *  galaxy takes the actor's defaults. Filling them
	 *  is the next step, not part of the texture split. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rolls")
	TArray<TObjectPtr<UVolumeTexture>> WarpDiscTextures;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rolls")
	TArray<TObjectPtr<UVolumeTexture>> WarpHaloTextures;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rolls")
	TArray<TObjectPtr<UVolumeTexture>> NoiseDiscTextures;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rolls")
	TArray<TObjectPtr<UVolumeTexture>> NoiseHaloTextures;

	/** THE PIPELINE, in order:
	 *
	 *    1. the exemplar
	 *    2. every listed range, each keyed to its own stream by parameter NAME
	 *    3. the texture draw, if the bag is non-empty
	 *    4. ApplyGenerationLogic
	 *
	 *  Not virtual -- the ORDER is the contract. A subclass that replaced this could
	 *  silently stop applying its own authored ranges, and nothing in the editor would
	 *  show it. Override the hook, which runs last and can overwrite anything the
	 *  ranges produced.
	 *
	 *  bInDefaultsOnly short-circuits at step 1 and returns the exemplar VERBATIM,
	 *  including skipping the hook. That is what makes default mode a clean comparison:
	 *  turn it off and everything that changed is generation. */
	FGalaxyProceduralParams Resolve(int32 InSeed, bool bInDefaultsOnly) const;

	/** Every authored range checked once: name resolves, name is rollable, Min <= Max,
	 *  no duplicates. Returns false and logs one line per problem.
	 *
	 *  MIN > MAX PRODUCES SILENT GARBAGE otherwise -- FRandRange with the bounds
	 *  inverted returns a value outside the intended interval, no clamp catches it,
	 *  and the galaxy just comes out wrong. Cheap to run at config load; the
	 *  alternative is discovering it during the trial-and-error phase, which is the
	 *  one phase where every galaxy already looks unfamiliar. */
	bool Validate() const;

	/** One line naming the archetype and the parameters that most define its
	 *  silhouette. Saves the spawn-and-eyeball cycle. */
	void LogPreview(int32 InSeed, bool bInDefaultsOnly) const;

	/** A named stream off this galaxy's seed, for a subclass writing its own rolls.
	 *
	 *  USE THIS RATHER THAN FRandomStream(InSeed). Two consumers seeded from the same
	 *  value draw the identical sequence, so a hand-written roll seeded directly would
	 *  alias against the archetype selection. Naming the draw also means adding one
	 *  later does not disturb the rolls already written -- see ProcSeed. */
	static FRandomStream ParameterStream(FName InChannel, int32 InSeed)
	{
		return ProcSeed::Stream(InSeed, ProcSeed::ChannelId(InChannel));
	}

	/** One range applied to one address, shaped by Bias and Quantize. Exposed so a
	 *  subclass can reuse the exact draw the generic path uses when it only wants to
	 *  reorder or condition rolls rather than replace their distribution. */
	static float RollRange(const FGalaxyParamRange& InRange, int32 InSeed);

	/** Every rollable parameter name, reflected off FGalaxyProceduralParams: float
	 *  members by name, colour and vector members expanded per component, object
	 *  members omitted. Backs the Parameter dropdown. */
	UFUNCTION()
	static TArray<FString> GetRollableParameterNames();

	/** Address of the float a parameter name designates, or nullptr if it does not
	 *  resolve. THE ONE PLACE the name grammar is interpreted -- Resolve, Validate and
	 *  the dropdown all go through it, so they cannot disagree about what a name
	 *  means. */
	static float* ResolveParameter(FGalaxyProceduralParams& InOutParams, FName InParameter);

protected:
	/** BESPOKE GENERATION. Runs last, after the exemplar and every range, so it can
	 *  read what was rolled and derive, correlate or override from it. The base
	 *  implementation does nothing, which is the correct behaviour for an archetype
	 *  that is only numbers.
	 *
	 *  Draw through ParameterStream, never FRandomStream(InSeed) directly.
	 *
	 *  Does NOT run in default mode -- the exemplar is meant to be verbatim. */
	virtual void ApplyGenerationLogic(FGalaxyProceduralParams& InOutParams, int32 InSeed) const {}
};